### ISSUE TITLE
Filecoin Wallet Error: Can't create a new wallet

### ISSUE THREAD

**Issue by inacali** [naszam/wfil#1]
coming with the following error

createWallet -> error Error: Request failed with status code 500
    at e.exports (createError.js:17)
    at e.exports (settle.js:19)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:63)

when trying to create a new wallet.

**Comment by naszam** [comment]
Hi @inacali,  thanks for sharing!

We're currently working on that.

cc @cristiam86

**Comment by naszam** [comment]
Hi @inacali,

Now the wallet should work!
We've integrated the Filecoin Wallet directly on the interface at [wfil.network](https://wfil.network)
Thanks!
